<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Configuration OHADA — Organisation pour l'Harmonisation en Afrique
    | du Droit des Affaires
    |--------------------------------------------------------------------------
    | 17 États membres — Traité de Port-Louis (1993, révisé 2008)
    */

    'countries' => [
        'BJ' => [
            'code'              => 'BJ',
            'name_fr'           => 'Bénin',
            'name_en'           => 'Benin',
            'capitale'          => 'Porto-Novo',
            'capitale_economique' => 'Cotonou',
            'currency'          => 'XOF',
            'langue_officielle' => 'fr',
            'timezone'          => 'Africa/Porto-Novo', // UTC+1
            'utc_offset'        => 1,
            'tel_prefix'        => '+229',
            'vat_rate'          => 18.0,
            'vat_name'          => 'TVA',
            'date_format'       => 'd/m/Y',
            'first_day_of_week' => 1, // Lundi
            'plan_comptable'    => 'SYSCOHADA',
            'rccm_format'       => 'RB/COT/\d{2}/A/\d{4,6}',
            'nif_name'          => 'IFU',
            'legal_form_types'  => ['SARL', 'SA', 'GIE', 'EI', 'SNC', 'SCS'],
        ],
        'BF' => [
            'code'              => 'BF',
            'name_fr'           => 'Burkina Faso',
            'name_en'           => 'Burkina Faso',
            'capitale'          => 'Ouagadougou',
            'capitale_economique' => 'Ouagadougou',
            'currency'          => 'XOF',
            'langue_officielle' => 'fr',
            'timezone'          => 'Africa/Ouagadougou', // UTC+0
            'utc_offset'        => 0,
            'tel_prefix'        => '+226',
            'vat_rate'          => 18.0,
            'vat_name'          => 'TVA',
            'date_format'       => 'd/m/Y',
            'first_day_of_week' => 1,
            'plan_comptable'    => 'SYSCOHADA',
            'rccm_format'       => 'RCCM-BF-OUA-\d{4}-[AB]-\d{4,6}',
            'nif_name'          => 'NIF',
            'legal_form_types'  => ['SARL', 'SA', 'GIE', 'EI', 'SNC'],
        ],
        'CM' => [
            'code'              => 'CM',
            'name_fr'           => 'Cameroun',
            'name_en'           => 'Cameroon',
            'capitale'          => 'Yaoundé',
            'capitale_economique' => 'Douala',
            'currency'          => 'XAF',
            'langue_officielle' => 'fr',
            'langue_secondaire' => 'en',
            'timezone'          => 'Africa/Douala', // UTC+1
            'utc_offset'        => 1,
            'tel_prefix'        => '+237',
            'vat_rate'          => 19.25,
            'vat_name'          => 'TVA',
            'date_format'       => 'd/m/Y',
            'first_day_of_week' => 1,
            'plan_comptable'    => 'SYSCOHADA',
            'rccm_format'       => 'RC/DLA/\d{4}/[AB]/\d{4,6}',
            'nif_name'          => 'NIU',
            'legal_form_types'  => ['SARL', 'SA', 'GIE', 'EI', 'SNC', 'SCS', 'SCP'],
        ],
        'CF' => [
            'code'              => 'CF',
            'name_fr'           => 'République Centrafricaine',
            'name_en'           => 'Central African Republic',
            'capitale'          => 'Bangui',
            'capitale_economique' => 'Bangui',
            'currency'          => 'XAF',
            'langue_officielle' => 'fr',
            'timezone'          => 'Africa/Bangui', // UTC+1
            'utc_offset'        => 1,
            'tel_prefix'        => '+236',
            'vat_rate'          => 19.0,
            'vat_name'          => 'TVA',
            'date_format'       => 'd/m/Y',
            'first_day_of_week' => 1,
            'plan_comptable'    => 'SYSCOHADA',
            'rccm_format'       => 'RCM-BGI-\d{4}-[AB]-\d{4,6}',
            'nif_name'          => 'NIF',
            'legal_form_types'  => ['SARL', 'SA', 'GIE', 'EI'],
        ],
        'KM' => [
            'code'              => 'KM',
            'name_fr'           => 'Comores',
            'name_en'           => 'Comoros',
            'capitale'          => 'Moroni',
            'capitale_economique' => 'Moroni',
            'currency'          => 'KMF',
            'langue_officielle' => 'fr',
            'timezone'          => 'Indian/Comoro', // UTC+3
            'utc_offset'        => 3,
            'tel_prefix'        => '+269',
            'vat_rate'          => 10.0,
            'vat_name'          => 'TVA',
            'date_format'       => 'd/m/Y',
            'first_day_of_week' => 0, // Dimanche (tradition islamique)
            'plan_comptable'    => 'SYSCOHADA',
            'rccm_format'       => 'RCCM-KM-\d{4}-[AB]-\d{4,6}',
            'nif_name'          => 'NIF',
            'legal_form_types'  => ['SARL', 'SA', 'GIE', 'EI'],
        ],
        'CG' => [
            'code'              => 'CG',
            'name_fr'           => 'Congo',
            'name_en'           => 'Republic of the Congo',
            'capitale'          => 'Brazzaville',
            'capitale_economique' => 'Pointe-Noire',
            'currency'          => 'XAF',
            'langue_officielle' => 'fr',
            'timezone'          => 'Africa/Brazzaville', // UTC+1
            'utc_offset'        => 1,
            'tel_prefix'        => '+242',
            'vat_rate'          => 18.0,
            'vat_name'          => 'TVA',
            'date_format'       => 'd/m/Y',
            'first_day_of_week' => 1,
            'plan_comptable'    => 'SYSCOHADA',
            'rccm_format'       => 'RCCM-BZV-\d{4}-[AB]-\d{4,6}',
            'nif_name'          => 'NIU',
            'legal_form_types'  => ['SARL', 'SA', 'GIE', 'EI', 'SNC'],
        ],
        'CI' => [
            'code'              => 'CI',
            'name_fr'           => 'Côte d\'Ivoire',
            'name_en'           => 'Ivory Coast',
            'capitale'          => 'Yamoussoukro',
            'capitale_economique' => 'Abidjan',
            'currency'          => 'XOF',
            'langue_officielle' => 'fr',
            'timezone'          => 'Africa/Abidjan', // UTC+0
            'utc_offset'        => 0,
            'tel_prefix'        => '+225',
            'vat_rate'          => 18.0,
            'vat_name'          => 'TVA',
            'date_format'       => 'd/m/Y',
            'first_day_of_week' => 1,
            'plan_comptable'    => 'SYSCOHADA',
            'rccm_format'       => 'CI-ABJ-\d{4}-[AB]-\d{4,6}',
            'nif_name'          => 'NCC',
            'nif_label'         => 'Numéro de Compte Contribuable',
            'legal_form_types'  => ['SARL', 'SA', 'GIE', 'EI', 'SNC', 'SCS', 'SCP', 'SARLU'],
            'dgi_url'           => 'https://www.dgi.gouv.ci',
        ],
        'GA' => [
            'code'              => 'GA',
            'name_fr'           => 'Gabon',
            'name_en'           => 'Gabon',
            'capitale'          => 'Libreville',
            'capitale_economique' => 'Port-Gentil',
            'currency'          => 'XAF',
            'langue_officielle' => 'fr',
            'timezone'          => 'Africa/Libreville', // UTC+1
            'utc_offset'        => 1,
            'tel_prefix'        => '+241',
            'vat_rate'          => 18.0,
            'vat_name'          => 'TVA',
            'date_format'       => 'd/m/Y',
            'first_day_of_week' => 1,
            'plan_comptable'    => 'SYSCOHADA',
            'rccm_format'       => 'RCCM-GA-LBV-\d{4}-[AB]-\d{4,6}',
            'nif_name'          => 'NIF',
            'legal_form_types'  => ['SARL', 'SA', 'GIE', 'EI', 'SNC'],
        ],
        'GN' => [
            'code'              => 'GN',
            'name_fr'           => 'Guinée',
            'name_en'           => 'Guinea',
            'capitale'          => 'Conakry',
            'capitale_economique' => 'Conakry',
            'currency'          => 'GNF',
            'langue_officielle' => 'fr',
            'timezone'          => 'Africa/Conakry', // UTC+0
            'utc_offset'        => 0,
            'tel_prefix'        => '+224',
            'vat_rate'          => 18.0,
            'vat_name'          => 'TVA',
            'date_format'       => 'd/m/Y',
            'first_day_of_week' => 1,
            'plan_comptable'    => 'SYSCOHADA',
            'rccm_format'       => 'RCCM-GN-CNK-\d{4}-[AB]-\d{4,6}',
            'nif_name'          => 'NIF',
            'legal_form_types'  => ['SARL', 'SA', 'GIE', 'EI'],
        ],
        'GW' => [
            'code'              => 'GW',
            'name_fr'           => 'Guinée-Bissau',
            'name_en'           => 'Guinea-Bissau',
            'capitale'          => 'Bissau',
            'capitale_economique' => 'Bissau',
            'currency'          => 'XOF',
            'langue_officielle' => 'pt',
            'timezone'          => 'Africa/Bissau', // UTC+0
            'utc_offset'        => 0,
            'tel_prefix'        => '+245',
            'vat_rate'          => 15.0,
            'vat_name'          => 'IVA',
            'date_format'       => 'd/m/Y',
            'first_day_of_week' => 1,
            'plan_comptable'    => 'SYSCOHADA',
            'rccm_format'       => 'RCCM-GW-\d{4}-[AB]-\d{4,6}',
            'nif_name'          => 'NIF',
            'legal_form_types'  => ['SARL', 'SA', 'GIE', 'EI'],
        ],
        'GQ' => [
            'code'              => 'GQ',
            'name_fr'           => 'Guinée Équatoriale',
            'name_en'           => 'Equatorial Guinea',
            'capitale'          => 'Malabo',
            'capitale_economique' => 'Bata',
            'currency'          => 'XAF',
            'langue_officielle' => 'es',
            'langue_secondaire' => 'fr',
            'timezone'          => 'Africa/Malabo', // UTC+1
            'utc_offset'        => 1,
            'tel_prefix'        => '+240',
            'vat_rate'          => 15.0,
            'vat_name'          => 'ISAVE',
            'date_format'       => 'd/m/Y',
            'first_day_of_week' => 1,
            'plan_comptable'    => 'SYSCOHADA',
            'rccm_format'       => 'RCCM-GQ-\d{4}-[AB]-\d{4,6}',
            'nif_name'          => 'NIF',
            'legal_form_types'  => ['SARL', 'SA', 'GIE', 'EI'],
        ],
        'ML' => [
            'code'              => 'ML',
            'name_fr'           => 'Mali',
            'name_en'           => 'Mali',
            'capitale'          => 'Bamako',
            'capitale_economique' => 'Bamako',
            'currency'          => 'XOF',
            'langue_officielle' => 'fr',
            'timezone'          => 'Africa/Bamako', // UTC+0
            'utc_offset'        => 0,
            'tel_prefix'        => '+223',
            'vat_rate'          => 18.0,
            'vat_name'          => 'TVA',
            'date_format'       => 'd/m/Y',
            'first_day_of_week' => 1,
            'plan_comptable'    => 'SYSCOHADA',
            'rccm_format'       => 'MA-BKO-\d{4}-[AB]-\d{4,6}',
            'nif_name'          => 'NIF',
            'legal_form_types'  => ['SARL', 'SA', 'GIE', 'EI', 'SNC'],
        ],
        'NE' => [
            'code'              => 'NE',
            'name_fr'           => 'Niger',
            'name_en'           => 'Niger',
            'capitale'          => 'Niamey',
            'capitale_economique' => 'Niamey',
            'currency'          => 'XOF',
            'langue_officielle' => 'fr',
            'timezone'          => 'Africa/Niamey', // UTC+1
            'utc_offset'        => 1,
            'tel_prefix'        => '+227',
            'vat_rate'          => 19.0,
            'vat_name'          => 'TVA',
            'date_format'       => 'd/m/Y',
            'first_day_of_week' => 1,
            'plan_comptable'    => 'SYSCOHADA',
            'rccm_format'       => 'RCCM-NE-NIM-\d{4}-[AB]-\d{4,6}',
            'nif_name'          => 'NIF',
            'legal_form_types'  => ['SARL', 'SA', 'GIE', 'EI'],
        ],
        'CD' => [
            'code'              => 'CD',
            'name_fr'           => 'République Démocratique du Congo',
            'name_en'           => 'Democratic Republic of the Congo',
            'capitale'          => 'Kinshasa',
            'capitale_economique' => 'Kinshasa',
            'currency'          => 'CDF',
            'langue_officielle' => 'fr',
            'timezone'          => 'Africa/Kinshasa', // UTC+1
            'utc_offset'        => 1,
            'tel_prefix'        => '+243',
            'vat_rate'          => 16.0,
            'vat_name'          => 'TVA',
            'date_format'       => 'd/m/Y',
            'first_day_of_week' => 1,
            'plan_comptable'    => 'SYSCOHADA',
            'rccm_format'       => 'CD/KIN/RCCM/\d{2}-[AB]-\d{4,6}',
            'nif_name'          => 'NIF',
            'legal_form_types'  => ['SARL', 'SA', 'GIE', 'EI', 'SNC'],
        ],
        'SN' => [
            'code'              => 'SN',
            'name_fr'           => 'Sénégal',
            'name_en'           => 'Senegal',
            'capitale'          => 'Dakar',
            'capitale_economique' => 'Dakar',
            'currency'          => 'XOF',
            'langue_officielle' => 'fr',
            'timezone'          => 'Africa/Dakar', // UTC+0
            'utc_offset'        => 0,
            'tel_prefix'        => '+221',
            'vat_rate'          => 18.0,
            'vat_name'          => 'TVA',
            'date_format'       => 'd/m/Y',
            'first_day_of_week' => 1,
            'plan_comptable'    => 'SYSCOHADA',
            'rccm_format'       => 'SN-DKR-\d{4}-[AB]-\d{4,6}',
            'nif_name'          => 'NINEA',
            'nif_label'         => 'Numéro d\'Identification Nationale des Entreprises et Associations',
            'legal_form_types'  => ['SARL', 'SA', 'GIE', 'EI', 'SNC', 'SCS'],
        ],
        'TD' => [
            'code'              => 'TD',
            'name_fr'           => 'Tchad',
            'name_en'           => 'Chad',
            'capitale'          => 'N\'Djamena',
            'capitale_economique' => 'N\'Djamena',
            'currency'          => 'XAF',
            'langue_officielle' => 'fr',
            'langue_secondaire' => 'ar',
            'timezone'          => 'Africa/Ndjamena', // UTC+1
            'utc_offset'        => 1,
            'tel_prefix'        => '+235',
            'vat_rate'          => 18.0,
            'vat_name'          => 'TVA',
            'date_format'       => 'd/m/Y',
            'first_day_of_week' => 0, // Dimanche (tradition islamique)
            'plan_comptable'    => 'SYSCOHADA',
            'rccm_format'       => 'TC/NDJ/RCCM/\d{4}-[AB]-\d{4,6}',
            'nif_name'          => 'NIF',
            'legal_form_types'  => ['SARL', 'SA', 'GIE', 'EI'],
        ],
        'TG' => [
            'code'              => 'TG',
            'name_fr'           => 'Togo',
            'name_en'           => 'Togo',
            'capitale'          => 'Lomé',
            'capitale_economique' => 'Lomé',
            'currency'          => 'XOF',
            'langue_officielle' => 'fr',
            'timezone'          => 'Africa/Lome', // UTC+0
            'utc_offset'        => 0,
            'tel_prefix'        => '+228',
            'vat_rate'          => 18.0,
            'vat_name'          => 'TVA',
            'date_format'       => 'd/m/Y',
            'first_day_of_week' => 1,
            'plan_comptable'    => 'SYSCOHADA',
            'rccm_format'       => 'TG-LOM-\d{4}-[AB]-\d{4,6}',
            'nif_name'          => 'RCCM',
            'legal_form_types'  => ['SARL', 'SA', 'GIE', 'EI', 'SNC'],
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Zones économiques régionales
    |--------------------------------------------------------------------------
    */
    'zones' => [
        'UEMOA' => [
            'name'     => 'Union Économique et Monétaire Ouest-Africaine',
            'currency' => 'XOF',
            'bank'     => 'BCEAO',
            'members'  => ['BJ', 'BF', 'CI', 'GW', 'ML', 'NE', 'SN', 'TG'],
        ],
        'CEMAC' => [
            'name'     => 'Communauté Économique et Monétaire de l\'Afrique Centrale',
            'currency' => 'XAF',
            'bank'     => 'BEAC',
            'members'  => ['CM', 'CF', 'CG', 'GA', 'GQ', 'TD'],
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Plan Comptable SYSCOHADA Révisé
    | Acte Uniforme portant organisation et harmonisation des comptabilités
    |--------------------------------------------------------------------------
    */
    'syscohada_classes' => [
        1 => 'Ressources durables',
        2 => 'Emplois stables',
        3 => 'Stocks',
        4 => 'Tiers',
        5 => 'Trésorerie',
        6 => 'Charges des activités ordinaires',
        7 => 'Produits des activités ordinaires',
        8 => 'Autres charges et autres produits',
        9 => 'Comptes de la comptabilité analytique de gestion',
    ],

    /*
    |--------------------------------------------------------------------------
    | Durées légales d'archivage
    |--------------------------------------------------------------------------
    */
    'archive_durations' => [
        'factures'              => 10, // années
        'contrats'              => 10,
        'documents_comptables'  => 10,
        'bulletins_paie'        => 5,
        'declarations_fiscales' => 10,
        'statuts_societe'       => 'permanent',
        'registre_commerce'     => 'permanent',
        'pv_ag'                 => 'permanent',
    ],

    /*
    |--------------------------------------------------------------------------
    | Références légales
    |--------------------------------------------------------------------------
    */
    'legal_references' => [
        'traite_ohada'    => 'Traité relatif à l\'Harmonisation du Droit des Affaires en Afrique (Port-Louis, 17 octobre 1993)',
        'au_comptabilite' => 'Acte Uniforme relatif au Droit comptable et à l\'Information Financière (AUDCIF)',
        'au_societes'     => 'Acte Uniforme relatif au Droit des Sociétés Commerciales et du Groupement d\'Intérêt Économique (AUSCGIE)',
        'syscohada'       => 'Système Comptable OHADA (SYSCOHADA Révisé, 2017)',
        'ccja'            => 'Cour Commune de Justice et d\'Arbitrage (CCJA)',
    ],
];
