<?php

namespace Database\Seeders;

use App\Models\PracticalCase;
use Illuminate\Database\Seeder;

class PracticalCasesSeeder extends Seeder
{
    public function run(): void
    {
        $cases = [

            // ── AGENDA (3) ────────────────────────────────────────────────────

            [
                'slug'                => 'agenda-planifier-reunion-direction',
                'category'            => 'agenda',
                'difficulty'          => 'beginner',
                'duration_minutes'    => 15,
                'prerequisites'       => [],
                'learning_objectives' => [
                    'Créer un événement depuis l\'agenda',
                    'Inviter des participants internes',
                    'Réserver une salle de réunion',
                    'Envoyer les invitations par e-mail',
                ],
                'order'      => 1,
                'is_featured' => true,
                'translations' => [
                    'fr' => [
                        'title'       => 'Planifier une réunion de direction avec 5 participants',
                        'description' => 'Apprenez à organiser une réunion formelle avec plusieurs participants, réserver une salle et envoyer les invitations depuis SECRETIS.',
                        'context'     => 'Vous êtes secrétaire de direction à la SARL TechBureau CI. Le Directeur Général vous demande d\'organiser une réunion de direction pour lundi prochain à 10h00, d\'une durée de 2 heures, avec les 4 directeurs de départements. La salle de conférence "Cocody" doit être réservée.',
                        'steps'       => [
                            'Accédez au module **Agenda** depuis le menu latéral (icône calendrier).',
                            'Cliquez sur le bouton **+ Nouvel événement** en haut à droite.',
                            'Renseignez le titre : "Réunion de direction — Bilan mensuel".',
                            'Sélectionnez la date : lundi prochain, de **10h00 à 12h00**.',
                            'Dans le champ **Participants**, recherchez et ajoutez les 4 directeurs un par un.',
                            'Dans **Lieu / Salle**, cliquez sur "Réserver une salle" et sélectionnez "Salle Cocody" (vérifiez la disponibilité).',
                            'Ajoutez une note dans **Description** : "Ordre du jour : bilan mensuel, projets en cours, budget Q3".',
                            'Activez l\'option **Envoyer des invitations par e-mail** (toggle en bas du formulaire).',
                            'Cliquez sur **Enregistrer**.',
                            'Vérifiez que l\'événement apparaît dans votre agenda et que les participants reçoivent une notification.',
                        ],
                        'expected_result' => 'L\'événement "Réunion de direction — Bilan mensuel" apparaît en bleu dans l\'agenda du lundi prochain. La salle Cocody est marquée comme réservée. Chaque participant reçoit un e-mail d\'invitation avec l\'option d\'accepter ou refuser.',
                    ],
                    'en' => [
                        'title'       => 'Schedule a Management Meeting with 5 Participants',
                        'description' => 'Learn to organize a formal meeting with multiple participants, book a room and send invitations from SECRETIS.',
                        'context'     => 'You are executive secretary at TechBureau CI. The General Manager asks you to schedule a management meeting for next Monday at 10:00 AM, 2 hours long, with 4 department directors. The "Cocody" conference room must be reserved.',
                        'steps'       => [
                            'Go to the **Agenda** module from the side menu (calendar icon).',
                            'Click the **+ New Event** button at the top right.',
                            'Enter the title: "Management Meeting — Monthly Review".',
                            'Select the date: next Monday, from **10:00 AM to 12:00 PM**.',
                            'In the **Participants** field, search and add the 4 directors one by one.',
                            'Under **Location / Room**, click "Reserve a Room" and select "Cocody Room" (check availability).',
                            'Add a note in **Description**: "Agenda: monthly review, ongoing projects, Q3 budget".',
                            'Enable the **Send email invitations** option (toggle at the bottom of the form).',
                            'Click **Save**.',
                            'Verify the event appears in your agenda and participants receive a notification.',
                        ],
                        'expected_result' => 'The "Management Meeting — Monthly Review" event appears in blue on next Monday. The Cocody room is marked as reserved. Each participant receives an email invitation with options to accept or decline.',
                    ],
                ],
            ],

            [
                'slug'                => 'agenda-evenement-recurrent',
                'category'            => 'agenda',
                'difficulty'          => 'intermediate',
                'duration_minutes'    => 20,
                'prerequisites'       => ['agenda-planifier-reunion-direction'],
                'learning_objectives' => [
                    'Créer un événement récurrent',
                    'Configurer la fréquence et les exceptions',
                    'Modifier une occurrence sans affecter les autres',
                ],
                'order'      => 2,
                'is_featured' => false,
                'translations' => [
                    'fr' => [
                        'title'       => 'Créer un événement récurrent pour la réunion hebdomadaire',
                        'description' => 'Maîtrisez la gestion des événements récurrents : réunion hebdomadaire tous les mardis, avec gestion des jours fériés.',
                        'context'     => 'Votre direction souhaite institutionnaliser une réunion d\'équipe tous les mardis à 8h30 (durée 30 min) jusqu\'à fin décembre. Certains mardis coïncidant avec des jours fériés, vous devez gérer les exceptions.',
                        'steps'       => [
                            'Dans **Agenda**, cliquez sur **+ Nouvel événement**.',
                            'Titre : "Réunion d\'équipe hebdomadaire".',
                            'Date de début : le prochain mardi à 8h30, durée 30 minutes.',
                            'Activez le toggle **Récurrence**.',
                            'Sélectionnez **Hebdomadaire**, cochez le jour **Mardi**.',
                            'Dans **Fin de récurrence**, choisissez **Date de fin** et sélectionnez le 31 décembre.',
                            'Enregistrez l\'événement récurrent.',
                            'Identifiez une date de jour férié (ex : 7 août — Fête nationale ivoirienne). Cliquez sur cette occurrence dans l\'agenda.',
                            'Choisissez **Modifier seulement cet événement**.',
                            'Changez la date au mercredi suivant ou supprimez uniquement cette occurrence.',
                            'Enregistrez la modification isolée.',
                        ],
                        'expected_result' => 'L\'agenda affiche la réunion tous les mardis jusqu\'au 31 décembre, sauf le jour férié modifié. En vue mensuelle, vous pouvez distinguer l\'occurrence modifiée par une couleur ou mention différente.',
                    ],
                    'en' => [
                        'title'       => 'Create a Recurring Event for the Weekly Meeting',
                        'description' => 'Master recurring event management: weekly meetings every Tuesday, with handling of public holidays.',
                        'context'     => 'Management wants to institutionalize a weekly team meeting every Tuesday at 8:30 AM (30 min) until end of December. Some Tuesdays coincide with public holidays, so you need to manage exceptions.',
                        'steps'       => [
                            'In **Agenda**, click **+ New Event**.',
                            'Title: "Weekly Team Meeting".',
                            'Start date: next Tuesday at 8:30 AM, 30 minutes duration.',
                            'Enable the **Recurrence** toggle.',
                            'Select **Weekly**, check the **Tuesday** day.',
                            'Under **End Recurrence**, choose **End Date** and select December 31.',
                            'Save the recurring event.',
                            'Find a public holiday (e.g., August 7 — Ivory Coast National Day). Click on that occurrence in the agenda.',
                            'Choose **Modify only this event**.',
                            'Change the date to the following Wednesday or delete only this occurrence.',
                            'Save the isolated modification.',
                        ],
                        'expected_result' => 'The agenda shows the meeting every Tuesday until December 31, except for the modified holiday. In monthly view, you can distinguish the modified occurrence by a different color or label.',
                    ],
                ],
            ],

            [
                'slug'                => 'agenda-conflits-planning',
                'category'            => 'agenda',
                'difficulty'          => 'advanced',
                'duration_minutes'    => 25,
                'prerequisites'       => ['agenda-evenement-recurrent'],
                'learning_objectives' => [
                    'Détecter les conflits de planning',
                    'Utiliser la vue disponibilité',
                    'Trouver un créneau commun libre',
                    'Proposer des alternatives automatiques',
                ],
                'order'      => 3,
                'is_featured' => false,
                'translations' => [
                    'fr' => [
                        'title'       => 'Gérer les conflits de planning et trouver un créneau libre',
                        'description' => 'Résolvez des conflits de planning complexes en utilisant la vue disponibilité et l\'assistant de créneau de SECRETIS.',
                        'context'     => 'Vous devez organiser une réunion avec 6 personnes dont les agendas sont très chargés. Plusieurs créneaux proposés créent des conflits. Vous devez utiliser l\'outil de disponibilité pour trouver le premier créneau commun libre cette semaine.',
                        'steps'       => [
                            'Dans **Agenda**, cliquez sur **Voir la disponibilité** (icône grille en haut).',
                            'Ajoutez les 6 participants dans la zone de recherche des disponibilités.',
                            'Définissez la plage de recherche : cette semaine, de 8h à 18h.',
                            'L\'outil affiche une grille : les zones rouges = indisponibles, vertes = libres pour tous.',
                            'Identifiez le premier créneau vert d\'au moins 1h.',
                            'Cliquez sur ce créneau pour créer directement un événement pré-rempli.',
                            'Ajoutez le titre "Réunion de synchronisation projet".',
                            'Envoyez les invitations et notez les conflits signalés.',
                            'Si aucun créneau n\'est disponible cette semaine, étendez la recherche à la semaine suivante.',
                            'Enregistrez l\'événement sur le créneau sélectionné.',
                        ],
                        'expected_result' => 'Un événement est créé sur le premier créneau commun disponible. Tous les participants reçoivent l\'invitation. Aucun conflit de planning n\'est signalé dans les agendas des 6 participants.',
                    ],
                    'en' => [
                        'title'       => 'Manage Scheduling Conflicts and Find Free Time Slots',
                        'description' => 'Resolve complex scheduling conflicts using the availability view and slot assistant in SECRETIS.',
                        'context'     => 'You need to organize a meeting with 6 people with very busy agendas. Several proposed slots create conflicts. You must use the availability tool to find the first common free slot this week.',
                        'steps'       => [
                            'In **Agenda**, click **View Availability** (grid icon at the top).',
                            'Add the 6 participants in the availability search area.',
                            'Set the search range: this week, from 8 AM to 6 PM.',
                            'The tool displays a grid: red zones = unavailable, green = free for all.',
                            'Identify the first green slot of at least 1 hour.',
                            'Click on that slot to directly create a pre-filled event.',
                            'Add the title "Project Sync Meeting".',
                            'Send invitations and note any reported conflicts.',
                            'If no slot is available this week, extend the search to next week.',
                            'Save the event on the selected slot.',
                        ],
                        'expected_result' => 'An event is created in the first common available slot. All participants receive the invitation. No scheduling conflicts are flagged in the 6 participants\' agendas.',
                    ],
                ],
            ],

            // ── GED (3) ───────────────────────────────────────────────────────

            [
                'slug'                => 'ged-importer-classer-documents',
                'category'            => 'ged',
                'difficulty'          => 'beginner',
                'duration_minutes'    => 20,
                'prerequisites'       => [],
                'learning_objectives' => [
                    'Importer des documents dans la GED',
                    'Créer une structure de dossiers',
                    'Classer les documents par type',
                    'Ajouter des métadonnées',
                ],
                'order'      => 4,
                'is_featured' => true,
                'translations' => [
                    'fr' => [
                        'title'       => 'Importer et classer 10 documents',
                        'description' => 'Prenez en main la GED en important un lot de documents, en créant une arborescence logique et en renseignant les métadonnées.',
                        'context'     => 'Votre service vient de recevoir 10 documents variés (contrats, factures, rapports). Vous devez les intégrer dans la GED avec un classement rigoureux pour faciliter la recherche ultérieure.',
                        'steps'       => [
                            'Accédez au module **Documents** depuis le menu latéral.',
                            'Créez un dossier racine "Entrants 2024" : cliquez **+ Nouveau dossier**.',
                            'À l\'intérieur, créez 3 sous-dossiers : "Contrats", "Factures", "Rapports".',
                            'Sélectionnez le dossier "Contrats", cliquez **Importer des fichiers**.',
                            'Glissez-déposez (ou sélectionnez) les fichiers de contrats.',
                            'Pour chaque fichier, renseignez : **Type** (Contrat), **Date du document**, **Référence** (ex: CTR-2024-001).',
                            'Répétez l\'opération pour les factures (dossier "Factures") et rapports (dossier "Rapports").',
                            'Utilisez la barre de recherche pour taper "CTR-2024-001" et vérifiez que le document apparaît.',
                            'Ajoutez un **tag** "Urgent" sur 2 documents nécessitant une action.',
                            'Vérifiez le tableau de bord Documents : le compteur doit afficher 10 documents importés.',
                        ],
                        'expected_result' => 'La GED contient 10 documents correctement classés dans 3 sous-dossiers. La recherche par référence fonctionne. Les documents taggés "Urgent" sont identifiables par un badge rouge.',
                    ],
                    'en' => [
                        'title'       => 'Import and Classify 10 Documents',
                        'description' => 'Get started with the DMS by importing a batch of documents, creating a logical folder structure, and filling in metadata.',
                        'context'     => 'Your department just received 10 various documents (contracts, invoices, reports). You must integrate them into the DMS with a rigorous classification for easy later retrieval.',
                        'steps'       => [
                            'Go to the **Documents** module from the side menu.',
                            'Create a root folder "Incoming 2024": click **+ New Folder**.',
                            'Inside, create 3 subfolders: "Contracts", "Invoices", "Reports".',
                            'Select the "Contracts" folder, click **Import Files**.',
                            'Drag and drop (or select) the contract files.',
                            'For each file, fill in: **Type** (Contract), **Document Date**, **Reference** (e.g., CTR-2024-001).',
                            'Repeat for invoices ("Invoices" folder) and reports ("Reports" folder).',
                            'Use the search bar to type "CTR-2024-001" and verify the document appears.',
                            'Add an **"Urgent"** tag to 2 documents requiring action.',
                            'Check the Documents dashboard: the counter should show 10 imported documents.',
                        ],
                        'expected_result' => 'The DMS contains 10 documents correctly classified in 3 subfolders. Search by reference works. Documents tagged "Urgent" are identifiable by a red badge.',
                    ],
                ],
            ],

            [
                'slug'                => 'ged-modele-courrier',
                'category'            => 'ged',
                'difficulty'          => 'intermediate',
                'duration_minutes'    => 30,
                'prerequisites'       => ['ged-importer-classer-documents'],
                'learning_objectives' => [
                    'Créer un modèle de document réutilisable',
                    'Définir des variables dynamiques',
                    'Générer un courrier depuis le modèle',
                    'Versionner un document',
                ],
                'order'      => 5,
                'is_featured' => false,
                'translations' => [
                    'fr' => [
                        'title'       => 'Créer un modèle de courrier officiel',
                        'description' => 'Créez un modèle de courrier administratif réutilisable avec des variables dynamiques (date, destinataire, objet).',
                        'context'     => 'Votre organisation envoie régulièrement des courriers d\'invitation aux partenaires. Vous souhaitez créer un modèle standard pour ne plus rédiger ces courriers de zéro à chaque fois.',
                        'steps'       => [
                            'Dans **Documents**, allez dans l\'onglet **Modèles**.',
                            'Cliquez **+ Nouveau modèle**, nommez-le "Courrier d\'invitation officielle".',
                            'Sélectionnez la catégorie **Correspondance** et le type **Courrier**.',
                            'Dans l\'éditeur, rédigez l\'en-tête : logo de l\'organisation (inséré automatiquement via {{organization.logo}}), nom, adresse.',
                            'Insérez les variables dynamiques : {{date_courrier}}, {{destinataire.nom}}, {{destinataire.titre}}, {{objet}}, {{lieu_evenement}}, {{date_evenement}}.',
                            'Rédigez le corps du courrier avec les formules de politesse standards.',
                            'Ajoutez la signature : "Le Directeur Général, {{signataire.nom}}".',
                            'Cliquez **Enregistrer le modèle**.',
                            'Testez en cliquant **Générer un courrier depuis ce modèle** : renseignez les variables pour un exemple concret.',
                            'Téléchargez le PDF généré et vérifiez la mise en page.',
                        ],
                        'expected_result' => 'Le modèle "Courrier d\'invitation officielle" est disponible dans la bibliothèque de modèles. La génération d\'un courrier depuis ce modèle prend moins de 2 minutes et produit un PDF prêt à envoyer.',
                    ],
                    'en' => [
                        'title'       => 'Create an Official Letter Template',
                        'description' => 'Create a reusable administrative letter template with dynamic variables (date, recipient, subject).',
                        'context'     => 'Your organization regularly sends invitation letters to partners. You want to create a standard template so you no longer have to draft these letters from scratch each time.',
                        'steps'       => [
                            'In **Documents**, go to the **Templates** tab.',
                            'Click **+ New Template**, name it "Official Invitation Letter".',
                            'Select category **Correspondence** and type **Letter**.',
                            'In the editor, draft the header: organization logo (auto-inserted via {{organization.logo}}), name, address.',
                            'Insert dynamic variables: {{letter_date}}, {{recipient.name}}, {{recipient.title}}, {{subject}}, {{event_location}}, {{event_date}}.',
                            'Draft the letter body with standard formal language.',
                            'Add the signature: "The General Manager, {{signatory.name}}".',
                            'Click **Save Template**.',
                            'Test by clicking **Generate a Letter from this Template**: fill in the variables for a concrete example.',
                            'Download the generated PDF and check the layout.',
                        ],
                        'expected_result' => 'The "Official Invitation Letter" template is available in the template library. Generating a letter from this template takes less than 2 minutes and produces a ready-to-send PDF.',
                    ],
                ],
            ],

            [
                'slug'                => 'ged-workflow-validation',
                'category'            => 'ged',
                'difficulty'          => 'advanced',
                'duration_minutes'    => 45,
                'prerequisites'       => ['ged-modele-courrier'],
                'learning_objectives' => [
                    'Configurer un workflow de validation documentaire',
                    'Définir les étapes de validation et les validateurs',
                    'Soumettre un document au workflow',
                    'Approuver ou rejeter en tant que validateur',
                ],
                'order'      => 6,
                'is_featured' => false,
                'translations' => [
                    'fr' => [
                        'title'       => 'Mettre en place un workflow de validation documentaire',
                        'description' => 'Configurez un circuit de validation en 3 étapes pour vos documents officiels avant publication.',
                        'context'     => 'Votre direction impose un circuit de validation pour tout courrier officiel sortant : (1) Vérification par l\'assistante de direction, (2) Validation par le chef de service, (3) Signature finale du DG. Vous devez configurer ce workflow dans SECRETIS.',
                        'steps'       => [
                            'Dans **Documents → Paramètres → Workflows**, cliquez **+ Nouveau workflow**.',
                            'Nommez-le "Validation courrier officiel sortant".',
                            'Associez-le au type de document : **Courrier**.',
                            'Ajoutez l\'étape 1 : Nom "Vérification initiale", Assignée à "Assistante de Direction", Délai 24h.',
                            'Ajoutez l\'étape 2 : Nom "Validation chef de service", Assignée au rôle "Chef de Service", Délai 24h.',
                            'Ajoutez l\'étape 3 : Nom "Signature DG", Assignée au rôle "Directeur Général", Délai 48h.',
                            'Activez l\'option "Notifier par e-mail à chaque étape".',
                            'Enregistrez le workflow et activez-le.',
                            'Testez : importez un courrier test, cliquez **Soumettre au workflow "Validation courrier officiel sortant"**.',
                            'Connectez-vous en tant que validateur de l\'étape 1, approuvez le document.',
                            'Vérifiez que le document passe à l\'étape 2 automatiquement.',
                        ],
                        'expected_result' => 'Le workflow est actif. Un courrier soumis progresse automatiquement entre les 3 étapes. Chaque validateur reçoit une notification e-mail. Le statut du document change : Brouillon → En validation → Validé → Signé.',
                    ],
                    'en' => [
                        'title'       => 'Set Up a Document Validation Workflow',
                        'description' => 'Configure a 3-step validation circuit for your official documents before publication.',
                        'context'     => 'Management requires a validation circuit for all outgoing official letters: (1) Check by executive assistant, (2) Validation by department head, (3) Final signature by CEO. You must configure this workflow in SECRETIS.',
                        'steps'       => [
                            'In **Documents → Settings → Workflows**, click **+ New Workflow**.',
                            'Name it "Outgoing Official Letter Validation".',
                            'Associate it with document type: **Letter**.',
                            'Add step 1: Name "Initial Check", Assigned to "Executive Assistant", Deadline 24h.',
                            'Add step 2: Name "Department Head Validation", Assigned to role "Department Head", Deadline 24h.',
                            'Add step 3: Name "CEO Signature", Assigned to role "General Manager", Deadline 48h.',
                            'Enable "Send email notification at each step".',
                            'Save and activate the workflow.',
                            'Test: import a test letter, click **Submit to workflow "Outgoing Official Letter Validation"**.',
                            'Log in as the step 1 validator and approve the document.',
                            'Verify the document automatically moves to step 2.',
                        ],
                        'expected_result' => 'The workflow is active. A submitted letter automatically progresses through 3 steps. Each validator receives an email notification. Document status changes: Draft → Under Validation → Validated → Signed.',
                    ],
                ],
            ],

            // ── TÂCHES (3) ────────────────────────────────────────────────────

            [
                'slug'                => 'tasks-creer-affecter',
                'category'            => 'tasks',
                'difficulty'          => 'beginner',
                'duration_minutes'    => 15,
                'prerequisites'       => [],
                'learning_objectives' => [
                    'Créer un projet',
                    'Ajouter des tâches avec priorité',
                    'Affecter des tâches aux membres',
                    'Définir des dates d\'échéance',
                ],
                'order'      => 7,
                'is_featured' => true,
                'translations' => [
                    'fr' => [
                        'title'       => 'Créer et affecter les tâches d\'un projet',
                        'description' => 'Créez un projet de A à Z et répartissez les tâches entre les membres de votre équipe.',
                        'context'     => 'Votre équipe doit organiser la journée portes ouvertes de l\'entreprise le mois prochain. Vous êtes chef de projet et devez créer le projet dans SECRETIS, le décomposer en tâches et les affecter aux 3 membres de votre équipe.',
                        'steps'       => [
                            'Accédez au module **Tâches & Projets**.',
                            'Cliquez **+ Nouveau projet**, nommez-le "Journée Portes Ouvertes 2024".',
                            'Définissez : date de début = aujourd\'hui, date de fin = le jour de l\'événement.',
                            'Ajoutez une description et sélectionnez les membres de l\'équipe (3 personnes).',
                            'Dans le projet, cliquez **+ Nouvelle tâche** et créez : "Préparer le programme" (priorité Haute, assignée à vous, échéance J-15).',
                            'Créez la tâche "Commander le matériel" (priorité Normale, assignée au membre 2, échéance J-10).',
                            'Créez la tâche "Envoyer les invitations" (priorité Haute, assignée au membre 3, échéance J-14).',
                            'Créez la tâche "Préparer la signalétique" (priorité Basse, assignée au membre 2, échéance J-3).',
                            'Créez la tâche "Briefing équipe le matin J" (priorité Haute, assignée à tous, échéance J-1).',
                            'Vérifiez que chaque membre voit ses tâches dans son tableau de bord personnel.',
                        ],
                        'expected_result' => 'Le projet "Journée Portes Ouvertes 2024" apparaît dans la liste des projets avec 5 tâches réparties entre les membres. Chaque membre reçoit une notification pour ses tâches et peut les voir dans "Mes tâches".',
                    ],
                    'en' => [
                        'title'       => 'Create and Assign Project Tasks',
                        'description' => 'Create a project from scratch and distribute tasks among your team members.',
                        'context'     => 'Your team must organize the company open day next month. You are the project manager and must create the project in SECRETIS, break it into tasks, and assign them to the 3 team members.',
                        'steps'       => [
                            'Go to the **Tasks & Projects** module.',
                            'Click **+ New Project**, name it "Open Day 2024".',
                            'Set: start date = today, end date = event day.',
                            'Add a description and select team members (3 people).',
                            'In the project, click **+ New Task** and create: "Prepare the program" (High priority, assigned to you, deadline D-15).',
                            'Create task "Order equipment" (Normal priority, assigned to member 2, deadline D-10).',
                            'Create task "Send invitations" (High priority, assigned to member 3, deadline D-14).',
                            'Create task "Prepare signage" (Low priority, assigned to member 2, deadline D-3).',
                            'Create task "Morning briefing on event day" (High priority, assigned to all, deadline D-1).',
                            'Verify each member sees their tasks in their personal dashboard.',
                        ],
                        'expected_result' => 'The "Open Day 2024" project appears in the projects list with 5 tasks distributed among members. Each member receives a notification for their tasks and can see them in "My Tasks".',
                    ],
                ],
            ],

            [
                'slug'                => 'tasks-kanban-equipe',
                'category'            => 'tasks',
                'difficulty'          => 'intermediate',
                'duration_minutes'    => 25,
                'prerequisites'       => ['tasks-creer-affecter'],
                'learning_objectives' => [
                    'Utiliser la vue Kanban',
                    'Déplacer des tâches entre colonnes',
                    'Créer des colonnes personnalisées',
                    'Filtrer par membre et priorité',
                ],
                'order'      => 8,
                'is_featured' => false,
                'translations' => [
                    'fr' => [
                        'title'       => 'Organiser le Kanban d\'une équipe',
                        'description' => 'Maîtrisez la vue Kanban pour piloter visuellement le flux de travail de votre équipe.',
                        'context'     => 'Votre équipe de 4 personnes gère simultanément plusieurs projets. Vous souhaitez avoir une vue d\'ensemble en Kanban pour voir ce que chacun fait et identifier les blocages.',
                        'steps'       => [
                            'Dans **Tâches & Projets**, ouvrez votre projet et passez en vue **Kanban** (icône colonnes).',
                            'Les colonnes par défaut : À faire, En cours, En révision, Terminé.',
                            'Ajoutez une colonne personnalisée "Bloqué" : cliquez **+ Ajouter une colonne**, nommez-la "Bloqué", choisissez la couleur rouge.',
                            'Faites glisser 2 tâches vers "En cours".',
                            'Faites glisser 1 tâche vers "Bloqué" (simulez un blocage).',
                            'Cliquez sur la tâche "Bloqué" et ajoutez un commentaire : "En attente de validation budget - @Marie".',
                            'Utilisez le filtre **Membre** pour n\'afficher que les tâches d\'un seul collaborateur.',
                            'Utilisez le filtre **Priorité** pour ne voir que les tâches Haute priorité.',
                            'Réorganisez les tâches par glisser-déposer pour prioriser.',
                            'Activez la vue **Regrouper par membre** pour une vision par personne.',
                        ],
                        'expected_result' => 'Le Kanban affiche toutes les tâches du projet réparties en colonnes. La colonne "Bloqué" est visible en rouge. Les filtres permettent de voir les tâches par membre ou par priorité en temps réel.',
                    ],
                    'en' => [
                        'title'       => 'Organize a Team\'s Kanban Board',
                        'description' => 'Master the Kanban view to visually manage your team\'s workflow.',
                        'context'     => 'Your 4-person team manages multiple projects simultaneously. You want a Kanban overview to see what everyone is doing and identify bottlenecks.',
                        'steps'       => [
                            'In **Tasks & Projects**, open your project and switch to **Kanban** view (columns icon).',
                            'Default columns: To Do, In Progress, In Review, Done.',
                            'Add a custom column "Blocked": click **+ Add Column**, name it "Blocked", choose red color.',
                            'Drag 2 tasks to "In Progress".',
                            'Drag 1 task to "Blocked" (simulate a blockage).',
                            'Click on the "Blocked" task and add a comment: "Waiting for budget approval - @Marie".',
                            'Use the **Member** filter to show only one collaborator\'s tasks.',
                            'Use the **Priority** filter to see only High priority tasks.',
                            'Reorganize tasks by drag-and-drop to prioritize.',
                            'Enable **Group by Member** view for a per-person vision.',
                        ],
                        'expected_result' => 'The Kanban shows all project tasks distributed in columns. The "Blocked" column is visible in red. Filters allow viewing tasks by member or priority in real time.',
                    ],
                ],
            ],

            [
                'slug'                => 'tasks-rapport-avancement',
                'category'            => 'tasks',
                'difficulty'          => 'advanced',
                'duration_minutes'    => 30,
                'prerequisites'       => ['tasks-kanban-equipe'],
                'learning_objectives' => [
                    'Générer un rapport d\'avancement projet',
                    'Exporter en PDF et Excel',
                    'Planifier un rapport automatique',
                    'Partager avec les parties prenantes',
                ],
                'order'      => 9,
                'is_featured' => false,
                'translations' => [
                    'fr' => [
                        'title'       => 'Générer un rapport d\'avancement projet',
                        'description' => 'Produisez un rapport complet d\'avancement projet avec métriques, exécution du planning et statut des tâches.',
                        'context'     => 'Votre directeur demande un rapport d\'avancement hebdomadaire pour chaque projet actif, à lui envoyer chaque vendredi à 17h. Vous devez configurer ce rapport automatique dans SECRETIS.',
                        'steps'       => [
                            'Dans votre projet, cliquez sur l\'onglet **Rapports**.',
                            'Sélectionnez **Rapport d\'avancement standard**.',
                            'Personnalisez les sections : taux d\'avancement global, tâches terminées cette semaine, tâches en retard, prochaines échéances.',
                            'Ajoutez le graphique d\'avancement (burndown ou bar chart).',
                            'Cliquez **Prévisualiser** pour vérifier le rendu.',
                            'Exportez en PDF : **Télécharger → PDF** — vérifiez la mise en page.',
                            'Exportez en Excel : **Télécharger → Excel** — vérifiez les données.',
                            'Cliquez **Planifier ce rapport** : fréquence Hebdomadaire, jour Vendredi, heure 17h00.',
                            'Destinataires : ajoutez l\'adresse e-mail de votre directeur.',
                            'Activez et enregistrez la planification.',
                        ],
                        'expected_result' => 'Le rapport d\'avancement est généré avec toutes les sections configurées. La planification est active : chaque vendredi à 17h, le rapport est automatiquement envoyé par e-mail au directeur. Un log de l\'envoi est visible dans l\'historique.',
                    ],
                    'en' => [
                        'title'       => 'Generate a Project Progress Report',
                        'description' => 'Produce a complete project progress report with metrics, schedule execution, and task status.',
                        'context'     => 'Your director requests a weekly progress report for each active project, to be sent every Friday at 5 PM. You must configure this automated report in SECRETIS.',
                        'steps'       => [
                            'In your project, click the **Reports** tab.',
                            'Select **Standard Progress Report**.',
                            'Customize sections: overall progress rate, tasks completed this week, overdue tasks, upcoming deadlines.',
                            'Add a progress chart (burndown or bar chart).',
                            'Click **Preview** to check the layout.',
                            'Export to PDF: **Download → PDF** — check the layout.',
                            'Export to Excel: **Download → Excel** — check the data.',
                            'Click **Schedule this Report**: Weekly frequency, Friday, 5:00 PM.',
                            'Recipients: add your director\'s email address.',
                            'Enable and save the schedule.',
                        ],
                        'expected_result' => 'The progress report is generated with all configured sections. The schedule is active: every Friday at 5 PM, the report is automatically emailed to the director. A send log is visible in the history.',
                    ],
                ],
            ],

            // ── VISITEURS (2) ─────────────────────────────────────────────────

            [
                'slug'                => 'visitors-enregistrement-groupe',
                'category'            => 'visitors',
                'difficulty'          => 'beginner',
                'duration_minutes'    => 10,
                'prerequisites'       => [],
                'learning_objectives' => [
                    'Enregistrer un visiteur individuel',
                    'Gérer l\'arrivée d\'un groupe',
                    'Générer des badges visiteur',
                    'Notifier le contact interne',
                ],
                'order'      => 10,
                'is_featured' => false,
                'translations' => [
                    'fr' => [
                        'title'       => 'Enregistrer l\'arrivée d\'un groupe de visiteurs',
                        'description' => 'Gérez l\'accueil d\'un groupe de 5 visiteurs : enregistrement, badges et notification du contact interne.',
                        'context'     => 'Un groupe de 5 délégués de la Chambre de Commerce vient visiter vos locaux pour un partenariat potentiel. Ils arrivent à l\'accueil. Vous devez les enregistrer rapidement et prévenir le Directeur Commercial de leur arrivée.',
                        'steps'       => [
                            'Accédez au module **Visiteurs** depuis le menu latéral.',
                            'Cliquez **+ Enregistrer une visite**.',
                            'Sélectionnez **Visite de groupe**.',
                            'Renseignez l\'organisation : "Chambre de Commerce d\'Abidjan", motif : "Visite partenariat".',
                            'Ajoutez le 1er visiteur : Nom, Prénom, Fonction (cliquez **+ Ajouter un visiteur** pour les suivants).',
                            'Ajoutez les 4 autres visiteurs de la même façon.',
                            'Dans **Contact interne**, recherchez et sélectionnez le Directeur Commercial.',
                            'Activez **Envoyer une notification** — le directeur reçoit un SMS/e-mail d\'alerte.',
                            'Cliquez **Enregistrer et Imprimer les badges**.',
                            'Les 5 badges s\'impriment. Distribuez-les aux visiteurs.',
                        ],
                        'expected_result' => 'Les 5 visiteurs sont enregistrés dans le registre des visiteurs. 5 badges sont générés avec nom, photo-placeholder, heure d\'arrivée et contact interne. Le Directeur Commercial reçoit une notification "Vos visiteurs sont arrivés : délégation CCA (5 personnes)".',
                    ],
                    'en' => [
                        'title'       => 'Register the Arrival of a Group of Visitors',
                        'description' => 'Manage the reception of a group of 5 visitors: registration, badges, and internal contact notification.',
                        'context'     => 'A group of 5 delegates from the Chamber of Commerce is visiting your premises for a potential partnership. They arrive at reception. You must quickly register them and notify the Commercial Director of their arrival.',
                        'steps'       => [
                            'Go to the **Visitors** module from the side menu.',
                            'Click **+ Register a Visit**.',
                            'Select **Group Visit**.',
                            'Enter the organization: "Chamber of Commerce Abidjan", purpose: "Partnership visit".',
                            'Add the 1st visitor: Last name, First name, Position (click **+ Add Visitor** for the others).',
                            'Add the other 4 visitors the same way.',
                            'In **Internal Contact**, search and select the Commercial Director.',
                            'Enable **Send Notification** — the director receives an SMS/email alert.',
                            'Click **Register and Print Badges**.',
                            'The 5 badges print. Distribute them to the visitors.',
                        ],
                        'expected_result' => 'The 5 visitors are registered in the visitor log. 5 badges are generated with name, photo placeholder, arrival time, and internal contact. The Commercial Director receives a notification "Your visitors have arrived: CCA delegation (5 people)".',
                    ],
                ],
            ],

            [
                'slug'                => 'visitors-protocole-vip',
                'category'            => 'visitors',
                'difficulty'          => 'intermediate',
                'duration_minutes'    => 20,
                'prerequisites'       => ['visitors-enregistrement-groupe'],
                'learning_objectives' => [
                    'Configurer un protocole d\'accueil VIP',
                    'Créer un type de visite personnalisé',
                    'Automatiser les notifications multi-niveaux',
                    'Configurer le badge VIP',
                ],
                'order'      => 11,
                'is_featured' => false,
                'translations' => [
                    'fr' => [
                        'title'       => 'Configurer le protocole d\'accueil VIP',
                        'description' => 'Mettez en place un protocole d\'accueil spécial pour les visites de très haute importance avec alertes automatiques en cascade.',
                        'context'     => 'Un ministre de tutelle doit visiter votre organisation. La Direction exige un protocole spécial : notification immédiate du DG et de son assistante dès l\'arrivée, badge distinctif rouge et or, et registre VIP séparé.',
                        'steps'       => [
                            'Dans **Visiteurs → Paramètres → Types de visite**, cliquez **+ Nouveau type**.',
                            'Nommez-le "Visite VIP / Institutionnelle", couleur : **Rouge foncé**.',
                            'Configurez les notifications automatiques : ajoutez le DG (e-mail + SMS), l\'Assistante DG (e-mail + push), le Directeur de Cabinet (e-mail).',
                            'Dans **Modèle de badge**, sélectionnez "Modèle Premium" (fond doré, logo officiel).',
                            'Activez "Registre séparé" pour isoler ces visites.',
                            'Enregistrez le type de visite.',
                            'Testez : créez une visite de test avec le type "VIP", nommez le visiteur "Test Ministre".',
                            'Vérifiez que les 3 notifications sont envoyées immédiatement.',
                            'Vérifiez que le badge généré est différent (couleurs VIP).',
                            'Consultez **Rapports → Registre VIP** pour vérifier que la visite test y figure.',
                        ],
                        'expected_result' => 'Le type de visite VIP est configuré. Lors d\'une visite VIP, le DG et son assistante reçoivent une notification push + e-mail en moins de 30 secondes. Le badge VIP est doré avec un fond distinctif. Les visites VIP sont isolées dans un registre dédié.',
                    ],
                    'en' => [
                        'title'       => 'Configure the VIP Reception Protocol',
                        'description' => 'Set up a special reception protocol for very high-importance visits with automatic cascading alerts.',
                        'context'     => 'A supervising minister is scheduled to visit your organization. Management requires a special protocol: immediate notification to the CEO and assistant upon arrival, distinctive red and gold badge, and a separate VIP register.',
                        'steps'       => [
                            'In **Visitors → Settings → Visit Types**, click **+ New Type**.',
                            'Name it "VIP / Institutional Visit", color: **Dark Red**.',
                            'Configure automatic notifications: add the CEO (email + SMS), CEO Assistant (email + push), Chief of Staff (email).',
                            'Under **Badge Template**, select "Premium Template" (gold background, official logo).',
                            'Enable "Separate Register" to isolate these visits.',
                            'Save the visit type.',
                            'Test: create a test visit with type "VIP", name the visitor "Test Minister".',
                            'Verify that the 3 notifications are sent immediately.',
                            'Verify the generated badge is different (VIP colors).',
                            'Check **Reports → VIP Register** to confirm the test visit appears.',
                        ],
                        'expected_result' => 'The VIP visit type is configured. During a VIP visit, the CEO and assistant receive a push + email notification within 30 seconds. The VIP badge has a gold background with distinctive design. VIP visits are isolated in a dedicated register.',
                    ],
                ],
            ],

            // ── RH (2) ────────────────────────────────────────────────────────

            [
                'slug'                => 'hr-fiches-poste',
                'category'            => 'hr',
                'difficulty'          => 'beginner',
                'duration_minutes'    => 20,
                'prerequisites'       => [],
                'learning_objectives' => [
                    'Créer des fiches de poste',
                    'Renseigner les informations RH',
                    'Affecter un employé à son poste',
                    'Gérer la structure hiérarchique',
                ],
                'order'      => 12,
                'is_featured' => false,
                'translations' => [
                    'fr' => [
                        'title'       => 'Créer les fiches de poste de l\'équipe',
                        'description' => 'Structurez votre équipe en créant les fiches de poste et en affecter les employés dans SECRETIS.',
                        'context'     => 'Vous venez d\'intégrer 3 nouveaux collaborateurs : un assistant administratif, une chargée de communication et un comptable. Vous devez créer leurs fiches de poste et les intégrer à l\'organigramme de votre département.',
                        'steps'       => [
                            'Accédez au module **RH** depuis le menu latéral.',
                            'Allez dans **Employés → + Nouvel employé**.',
                            'Créez la fiche de "Kouamé Brou" : Poste = "Assistant Administratif", Département = "Direction Générale", Date d\'entrée = aujourd\'hui.',
                            'Renseignez : type de contrat (CDI/CDD), période d\'essai, salaire (si applicable), responsable hiérarchique.',
                            'Ajoutez une photo et les coordonnées professionnelles.',
                            'Enregistrez et créez la 2e fiche : "Aïssatou Diallo", Poste = "Chargée de Communication".',
                            'Créez la 3e fiche : "Kofi Mensah", Poste = "Comptable", Département = "Finance".',
                            'Allez dans **Organigramme** pour vérifier que les 3 nouveaux employés apparaissent dans la bonne structure.',
                            'Vérifiez les droits d\'accès SECRETIS attribués automatiquement selon leur poste.',
                            'Envoyez un e-mail de bienvenue depuis la fiche employé (bouton "Envoyer e-mail de bienvenue").',
                        ],
                        'expected_result' => 'Les 3 fiches de poste sont créées et visibles dans la liste des employés. L\'organigramme est mis à jour avec les nouveaux postes. Chaque employé reçoit un e-mail de bienvenue avec ses identifiants SECRETIS.',
                    ],
                    'en' => [
                        'title'       => 'Create Team Job Profiles',
                        'description' => 'Structure your team by creating job profiles and assigning employees in SECRETIS.',
                        'context'     => 'You just onboarded 3 new colleagues: an administrative assistant, a communications officer, and an accountant. You must create their job profiles and integrate them into your department\'s org chart.',
                        'steps'       => [
                            'Go to the **HR** module from the side menu.',
                            'Go to **Employees → + New Employee**.',
                            'Create the profile for "Kouamé Brou": Position = "Administrative Assistant", Department = "General Management", Start Date = today.',
                            'Fill in: contract type (permanent/fixed-term), probation period, salary (if applicable), line manager.',
                            'Add a photo and professional contact details.',
                            'Save and create the 2nd profile: "Aïssatou Diallo", Position = "Communications Officer".',
                            'Create the 3rd profile: "Kofi Mensah", Position = "Accountant", Department = "Finance".',
                            'Go to **Org Chart** to verify the 3 new employees appear in the correct structure.',
                            'Check the SECRETIS access rights automatically assigned based on their position.',
                            'Send a welcome email from the employee profile (button "Send Welcome Email").',
                        ],
                        'expected_result' => 'The 3 job profiles are created and visible in the employee list. The org chart is updated with the new positions. Each employee receives a welcome email with their SECRETIS credentials.',
                    ],
                ],
            ],

            [
                'slug'                => 'hr-planifier-conges',
                'category'            => 'hr',
                'difficulty'          => 'intermediate',
                'duration_minutes'    => 25,
                'prerequisites'       => ['hr-fiches-poste'],
                'learning_objectives' => [
                    'Soumettre une demande de congé',
                    'Valider ou refuser en tant que manager',
                    'Gérer le planning des congés de l\'équipe',
                    'Gérer les conflits de congés',
                ],
                'order'      => 13,
                'is_featured' => false,
                'translations' => [
                    'fr' => [
                        'title'       => 'Planifier les congés du mois',
                        'description' => 'Gérez les demandes de congés pour le mois à venir : soumission, validation, conflits et planning visuel.',
                        'context'     => '3 membres de votre équipe souhaitent prendre des congés ce mois-ci. Deux d\'entre eux ont des demandes qui se chevauchent sur la même semaine. Vous devez arbitrer et valider les congés de façon à toujours avoir au moins 2 personnes présentes.',
                        'steps'       => [
                            'Dans **RH → Congés**, consultez le planning du mois sous forme de calendrier.',
                            'Identificez les jours disponibles restants par employé (solde de congés).',
                            'En tant qu\'employé 1 : soumettez une demande de congé du 15 au 19 (5 jours ouvrables).',
                            'En tant qu\'employé 2 : soumettez une demande qui chevauche : du 17 au 21.',
                            'En tant que manager, allez dans **Demandes en attente** : vous voyez les 2 demandes en conflit signalées en orange.',
                            'Approuvez la demande de l\'employé 1 (première demande reçue).',
                            'Pour l\'employé 2 : cliquez **Proposer des alternatives** — le système suggère d\'autres créneaux sans conflit.',
                            'Proposez à l\'employé 2 les dates du 22 au 26, ajoutez un commentaire explicatif.',
                            'Approuvez la demande modifiée de l\'employé 2.',
                            'Vérifiez le planning du mois : le calendrier affiche les congés validés sans conflit.',
                        ],
                        'expected_result' => 'Les congés des 3 employés sont planifiés sans conflit. Le calendrier des congés du mois est visible par toute l\'équipe. Les employés reçoivent un e-mail de confirmation. Le manager a toujours au moins 2 personnes présentes chaque semaine.',
                    ],
                    'en' => [
                        'title'       => 'Plan the Month\'s Leave Schedule',
                        'description' => 'Manage leave requests for the coming month: submission, approval, conflicts, and visual planning.',
                        'context'     => '3 team members want to take leave this month. Two of them have overlapping requests for the same week. You must arbitrate and approve leave in a way that always keeps at least 2 people present.',
                        'steps'       => [
                            'In **HR → Leave**, view the month\'s schedule as a calendar.',
                            'Identify remaining available days per employee (leave balance).',
                            'As employee 1: submit a leave request for the 15th to 19th (5 working days).',
                            'As employee 2: submit an overlapping request: 17th to 21st.',
                            'As manager, go to **Pending Requests**: you see the 2 conflicting requests flagged in orange.',
                            'Approve employee 1\'s request (first request received).',
                            'For employee 2: click **Suggest Alternatives** — the system suggests other slots without conflict.',
                            'Propose dates of the 22nd to 26th for employee 2, add an explanatory comment.',
                            'Approve employee 2\'s modified request.',
                            'Check the month\'s schedule: the calendar shows approved leave without conflict.',
                        ],
                        'expected_result' => 'The 3 employees\' leave is scheduled without conflict. The monthly leave calendar is visible to the whole team. Employees receive a confirmation email. The manager always has at least 2 people present each week.',
                    ],
                ],
            ],

            // ── COMPTABILITÉ (2) ──────────────────────────────────────────────

            [
                'slug'                => 'accounting-note-frais',
                'category'            => 'accounting',
                'difficulty'          => 'beginner',
                'duration_minutes'    => 15,
                'prerequisites'       => [],
                'learning_objectives' => [
                    'Créer une note de frais',
                    'Ajouter des justificatifs',
                    'Soumettre à validation',
                    'Suivre le remboursement',
                ],
                'order'      => 14,
                'is_featured' => false,
                'translations' => [
                    'fr' => [
                        'title'       => 'Saisir une note de frais',
                        'description' => 'Créez une note de frais complète avec justificatifs et soumettez-la à validation pour remboursement.',
                        'context'     => 'Vous revenez d\'un déplacement professionnel à Yamoussoukro (2 jours). Vous avez des frais de transport (bus 12 000 XOF), d\'hébergement (hôtel 45 000 XOF) et de repas (2 × 5 000 XOF). Vous devez saisir votre note de frais dans SECRETIS.',
                        'steps'       => [
                            'Accédez au module **Comptabilité → Notes de frais**.',
                            'Cliquez **+ Nouvelle note de frais**.',
                            'Titre : "Déplacement Yamoussoukro — [dates]", catégorie : "Déplacement professionnel".',
                            'Ajoutez la ligne 1 : Type = "Transport", Description = "Bus Abidjan-Yamoussoukro A/R", Montant = 12 000 XOF, Date du reçu.',
                            'Cliquez **+ Ajouter une ligne** et saisissez l\'hébergement : 45 000 XOF, pièce jointe = photo du reçu hôtel.',
                            'Ajoutez 2 lignes de repas : 5 000 XOF chacune.',
                            'Le total calculé automatiquement : **67 000 XOF**.',
                            'Dans **Justificatifs**, importez les photos de vos reçus (photo depuis mobile ou fichier).',
                            'Sélectionnez le **Centre de coût** : "Direction Générale / Missions".',
                            'Cliquez **Soumettre pour validation** — votre responsable reçoit une notification.',
                        ],
                        'expected_result' => 'La note de frais de 67 000 XOF est soumise et visible dans "En attente de validation". Votre responsable reçoit une notification avec le récapitulatif. Vous pouvez suivre l\'état du remboursement dans "Mes notes de frais".',
                    ],
                    'en' => [
                        'title'       => 'Submit an Expense Report',
                        'description' => 'Create a complete expense report with receipts and submit it for approval and reimbursement.',
                        'context'     => 'You return from a 2-day business trip to Yamoussoukro. You have transport expenses (bus 12,000 XOF), accommodation (hotel 45,000 XOF), and meals (2 × 5,000 XOF). You must enter your expense report in SECRETIS.',
                        'steps'       => [
                            'Go to **Accounting → Expense Reports**.',
                            'Click **+ New Expense Report**.',
                            'Title: "Trip to Yamoussoukro — [dates]", category: "Business Travel".',
                            'Add line 1: Type = "Transport", Description = "Bus Abidjan-Yamoussoukro round trip", Amount = 12,000 XOF, receipt date.',
                            'Click **+ Add Line** and enter accommodation: 45,000 XOF, attachment = hotel receipt photo.',
                            'Add 2 meal lines: 5,000 XOF each.',
                            'Auto-calculated total: **67,000 XOF**.',
                            'Under **Receipts**, upload photos of your receipts (from mobile or file).',
                            'Select the **Cost Center**: "General Management / Missions".',
                            'Click **Submit for Validation** — your manager receives a notification.',
                        ],
                        'expected_result' => 'The 67,000 XOF expense report is submitted and visible in "Pending Validation". Your manager receives a notification with the summary. You can track the reimbursement status in "My Expense Reports".',
                    ],
                ],
            ],

            [
                'slug'                => 'accounting-rapport-depenses',
                'category'            => 'accounting',
                'difficulty'          => 'intermediate',
                'duration_minutes'    => 20,
                'prerequisites'       => ['accounting-note-frais'],
                'learning_objectives' => [
                    'Générer un rapport de dépenses mensuel',
                    'Filtrer par catégorie et département',
                    'Exporter en Excel et PDF',
                    'Analyser les tendances',
                ],
                'order'      => 15,
                'is_featured' => false,
                'translations' => [
                    'fr' => [
                        'title'       => 'Générer un rapport de dépenses mensuel',
                        'description' => 'Produisez un rapport complet de toutes les dépenses du mois avec analyse par catégorie et département.',
                        'context'     => 'Fin de mois : votre DAF demande un rapport consolidé de toutes les dépenses de l\'organisation pour le mois écoulé, avec une ventilation par département et par catégorie de dépense.',
                        'steps'       => [
                            'Dans **Comptabilité → Rapports**, sélectionnez **Rapport de dépenses**.',
                            'Définissez la période : premier au dernier jour du mois écoulé.',
                            'Laissez le filtre Département sur "Tous les départements".',
                            'Cliquez **Générer le rapport**.',
                            'Le rapport s\'affiche avec : total général, ventilation par département (barres), ventilation par catégorie (camembert).',
                            'Filtrez ensuite par département "Finance" pour voir les dépenses de ce seul département.',
                            'Filtrez par catégorie "Déplacements" pour voir tous les frais de mission.',
                            'Cliquez **Exporter → PDF** pour obtenir la version imprimable.',
                            'Cliquez **Exporter → Excel** pour obtenir les données brutes.',
                            'Vérifiez l\'onglet "Tendances" : comparaison avec le mois précédent.',
                        ],
                        'expected_result' => 'Le rapport affiche le total des dépenses du mois, ventilé par département et catégorie. Les graphiques sont clairs. L\'export PDF est imprimable et professionnel. L\'export Excel contient toutes les lignes de dépenses avec métadonnées.',
                    ],
                    'en' => [
                        'title'       => 'Generate a Monthly Expense Report',
                        'description' => 'Produce a comprehensive report of all monthly expenses with analysis by category and department.',
                        'context'     => 'End of month: your CFO requests a consolidated report of all organizational expenses for the past month, with a breakdown by department and expense category.',
                        'steps'       => [
                            'In **Accounting → Reports**, select **Expense Report**.',
                            'Set the period: first to last day of the past month.',
                            'Leave the Department filter on "All Departments".',
                            'Click **Generate Report**.',
                            'The report displays: grand total, breakdown by department (bars), breakdown by category (pie chart).',
                            'Then filter by department "Finance" to see only that department\'s expenses.',
                            'Filter by category "Travel" to see all travel expenses.',
                            'Click **Export → PDF** for the printable version.',
                            'Click **Export → Excel** for the raw data.',
                            'Check the "Trends" tab: comparison with the previous month.',
                        ],
                        'expected_result' => 'The report shows the month\'s total expenses, broken down by department and category. Charts are clear. The PDF export is printable and professional. The Excel export contains all expense lines with metadata.',
                    ],
                ],
            ],

            // ── RAPPORTS (2) ──────────────────────────────────────────────────

            [
                'slug'                => 'reporting-rapport-personnalise',
                'category'            => 'reporting',
                'difficulty'          => 'intermediate',
                'duration_minutes'    => 30,
                'prerequisites'       => [],
                'learning_objectives' => [
                    'Utiliser le Report Builder',
                    'Sélectionner les sources de données',
                    'Configurer les graphiques',
                    'Enregistrer et partager un rapport',
                ],
                'order'      => 16,
                'is_featured' => false,
                'translations' => [
                    'fr' => [
                        'title'       => 'Créer un rapport personnalisé avec le Report Builder',
                        'description' => 'Utilisez le Report Builder pour créer un tableau de bord personnalisé combinant plusieurs sources de données.',
                        'context'     => 'Votre direction souhaite un rapport mensuel combinant : le nombre de visiteurs reçus, les réunions tenues, les documents traités et les tâches complétées. Un seul rapport pour piloter l\'activité globale.',
                        'steps'       => [
                            'Accédez à **Rapports → Report Builder**.',
                            'Cliquez **+ Nouveau rapport**, nommez-le "Tableau de bord activité mensuelle".',
                            'Dans **Sources de données**, ajoutez : Visiteurs, Agenda/Réunions, Documents, Tâches.',
                            'Bloc 1 : **Carte KPI** — champ = "Visiteurs / Nombre total", période = mois en cours.',
                            'Bloc 2 : **Carte KPI** — champ = "Réunions / Nombre tenu", période = mois en cours.',
                            'Bloc 3 : **Graphique barres** — "Tâches complétées par semaine" (axe X = semaine, axe Y = nombre).',
                            'Bloc 4 : **Graphique courbes** — "Documents traités vs mois précédent".',
                            'Réorganisez les blocs par glisser-déposer selon la mise en page souhaitée.',
                            'Cliquez **Enregistrer**, puis **Partager** avec votre DG (lecture seule).',
                            'Cliquez **Prévisualiser** pour valider le rendu final.',
                        ],
                        'expected_result' => 'Le rapport "Tableau de bord activité mensuelle" est créé avec 4 blocs de données. Il est accessible par le DG en lecture seule. Toutes les métriques se mettent à jour automatiquement chaque jour.',
                    ],
                    'en' => [
                        'title'       => 'Create a Custom Report with the Report Builder',
                        'description' => 'Use the Report Builder to create a custom dashboard combining multiple data sources.',
                        'context'     => 'Management wants a monthly report combining: number of visitors received, meetings held, documents processed, and tasks completed — one single report to monitor overall activity.',
                        'steps'       => [
                            'Go to **Reports → Report Builder**.',
                            'Click **+ New Report**, name it "Monthly Activity Dashboard".',
                            'In **Data Sources**, add: Visitors, Agenda/Meetings, Documents, Tasks.',
                            'Block 1: **KPI Card** — field = "Visitors / Total count", period = current month.',
                            'Block 2: **KPI Card** — field = "Meetings / Held count", period = current month.',
                            'Block 3: **Bar Chart** — "Tasks completed per week" (X-axis = week, Y-axis = count).',
                            'Block 4: **Line Chart** — "Documents processed vs previous month".',
                            'Rearrange blocks by drag-and-drop to your preferred layout.',
                            'Click **Save**, then **Share** with your CEO (read-only).',
                            'Click **Preview** to validate the final layout.',
                        ],
                        'expected_result' => 'The "Monthly Activity Dashboard" report is created with 4 data blocks. It is accessible by the CEO in read-only mode. All metrics update automatically each day.',
                    ],
                ],
            ],

            [
                'slug'                => 'reporting-rapport-automatique',
                'category'            => 'reporting',
                'difficulty'          => 'advanced',
                'duration_minutes'    => 25,
                'prerequisites'       => ['reporting-rapport-personnalise'],
                'learning_objectives' => [
                    'Planifier un rapport automatique hebdomadaire',
                    'Configurer les destinataires',
                    'Tester l\'envoi immédiat',
                    'Consulter le journal d\'envois',
                ],
                'order'      => 17,
                'is_featured' => false,
                'translations' => [
                    'fr' => [
                        'title'       => 'Planifier un rapport hebdomadaire automatique',
                        'description' => 'Configurez l\'envoi automatique hebdomadaire d\'un rapport par e-mail à une liste de destinataires.',
                        'context'     => 'Votre DG souhaite recevoir chaque lundi matin à 7h un e-mail récapitulatif de l\'activité de la semaine précédente, avec les métriques clés au format PDF. Il souhaite aussi que les directeurs de département reçoivent uniquement les métriques de leur service.',
                        'steps'       => [
                            'Dans **Rapports**, ouvrez le rapport "Tableau de bord activité mensuelle" créé précédemment.',
                            'Cliquez **Planifier → Nouvelle planification**.',
                            'Fréquence : **Hebdomadaire**, jour : **Lundi**, heure : **07h00**.',
                            'Format d\'envoi : **PDF** joint à un e-mail.',
                            'Groupe 1 — Destinataires : DG ; Contenu : rapport complet.',
                            'Cliquez **+ Ajouter un groupe de destinataires**.',
                            'Groupe 2 — Destinataires : tous les directeurs ; Filtre : "uniquement leur département".',
                            'Objet de l\'e-mail : "SECRETIS — Rapport hebdomadaire {{semaine}} — {{organisation}}".',
                            'Activez la planification et cliquez **Tester maintenant** pour envoyer immédiatement.',
                            'Vérifiez la réception de l\'e-mail test et consultez **Journal → Historique des envois**.',
                        ],
                        'expected_result' => 'La planification est active. Chaque lundi à 7h, le DG reçoit le rapport complet en PDF et les directeurs reçoivent leur rapport filtré. Le journal d\'envoi confirme chaque envoi avec horodatage et liste des destinataires.',
                    ],
                    'en' => [
                        'title'       => 'Schedule an Automated Weekly Report',
                        'description' => 'Configure the automatic weekly email delivery of a report to a list of recipients.',
                        'context'     => 'Your CEO wants to receive a summary email every Monday morning at 7 AM with the previous week\'s activity metrics in PDF format. Department directors should only receive their department\'s metrics.',
                        'steps'       => [
                            'In **Reports**, open the "Monthly Activity Dashboard" report created earlier.',
                            'Click **Schedule → New Schedule**.',
                            'Frequency: **Weekly**, day: **Monday**, time: **7:00 AM**.',
                            'Send format: **PDF** attached to an email.',
                            'Group 1 — Recipients: CEO; Content: full report.',
                            'Click **+ Add Recipient Group**.',
                            'Group 2 — Recipients: all directors; Filter: "their department only".',
                            'Email subject: "SECRETIS — Weekly Report {{week}} — {{organization}}".',
                            'Enable the schedule and click **Test Now** to send immediately.',
                            'Check receipt of the test email and view **Log → Send History**.',
                        ],
                        'expected_result' => 'The schedule is active. Every Monday at 7 AM, the CEO receives the full PDF report and directors receive their filtered report. The send log confirms each delivery with timestamp and recipient list.',
                    ],
                ],
            ],

            // ── ADMIN (3) ─────────────────────────────────────────────────────

            [
                'slug'                => 'admin-ajouter-utilisateur',
                'category'            => 'admin',
                'difficulty'          => 'beginner',
                'duration_minutes'    => 15,
                'prerequisites'       => [],
                'learning_objectives' => [
                    'Créer un compte utilisateur',
                    'Assigner un rôle',
                    'Configurer les modules accessibles',
                    'Envoyer l\'invitation de bienvenue',
                ],
                'order'      => 18,
                'is_featured' => true,
                'translations' => [
                    'fr' => [
                        'title'       => 'Ajouter et configurer un nouvel utilisateur',
                        'description' => 'Créez un compte pour un nouvel employé, attribuez-lui un rôle et configurez ses accès aux modules.',
                        'context'     => 'Vous venez de recruter une nouvelle assistante de direction, Mme Fatou Koné. Elle doit avoir accès à SECRETIS avec les modules Agenda, Documents, et Visiteurs, sans accès à la Comptabilité ni à l\'Administration.',
                        'steps'       => [
                            'Accédez à **Paramètres → Utilisateurs → + Nouvel utilisateur**.',
                            'Renseignez : Prénom = "Fatou", Nom = "Koné", E-mail professionnel = "f.kone@votre-org.com".',
                            'Sélectionnez le **Rôle** = "Assistant(e) de direction" (ou créez ce rôle si inexistant).',
                            'Dans **Modules accessibles**, cochez : Agenda ✓, Documents ✓, Visiteurs ✓.',
                            'Décochez : Comptabilité ✗, Administration ✗, RH (lecture seule).',
                            'Définissez la **langue** : Français, **fuseau horaire** : Africa/Abidjan.',
                            'Activez **Envoi automatique de l\'e-mail de bienvenue**.',
                            'Cliquez **Créer l\'utilisateur**.',
                            'Vérifiez dans la liste des utilisateurs que "Fatou Koné" apparaît avec le statut "Invitation envoyée".',
                            'Testez la connexion avec le compte de Fatou pour vérifier qu\'elle voit uniquement les bons modules.',
                        ],
                        'expected_result' => 'Le compte de Fatou Koné est créé. Elle reçoit un e-mail avec un lien pour définir son mot de passe. Après connexion, son menu ne montre que Agenda, Documents et Visiteurs. Aucun accès à Comptabilité ni Admin.',
                    ],
                    'en' => [
                        'title'       => 'Add and Configure a New User',
                        'description' => 'Create an account for a new employee, assign a role, and configure module access.',
                        'context'     => 'You just recruited a new executive assistant, Ms. Fatou Koné. She needs access to SECRETIS with the Agenda, Documents, and Visitors modules, but no access to Accounting or Administration.',
                        'steps'       => [
                            'Go to **Settings → Users → + New User**.',
                            'Fill in: First Name = "Fatou", Last Name = "Koné", Work Email = "f.kone@your-org.com".',
                            'Select **Role** = "Executive Assistant" (or create this role if it doesn\'t exist).',
                            'Under **Accessible Modules**, check: Agenda ✓, Documents ✓, Visitors ✓.',
                            'Uncheck: Accounting ✗, Administration ✗, HR (read-only).',
                            'Set **Language**: French, **Time Zone**: Africa/Abidjan.',
                            'Enable **Automatic welcome email**.',
                            'Click **Create User**.',
                            'Verify in the user list that "Fatou Koné" appears with status "Invitation Sent".',
                            'Test login with Fatou\'s account to verify she only sees the correct modules.',
                        ],
                        'expected_result' => 'Fatou Koné\'s account is created. She receives an email with a link to set her password. After login, her menu shows only Agenda, Documents, and Visitors. No access to Accounting or Admin.',
                    ],
                ],
            ],

            [
                'slug'                => 'admin-permissions-role',
                'category'            => 'admin',
                'difficulty'          => 'advanced',
                'duration_minutes'    => 30,
                'prerequisites'       => ['admin-ajouter-utilisateur'],
                'learning_objectives' => [
                    'Créer un rôle personnalisé',
                    'Configurer les permissions fines',
                    'Appliquer le rôle à plusieurs utilisateurs',
                    'Tester et valider les permissions',
                ],
                'order'      => 19,
                'is_featured' => false,
                'translations' => [
                    'fr' => [
                        'title'       => 'Configurer les permissions d\'un rôle personnalisé',
                        'description' => 'Créez un rôle "Chargé de clientèle" avec des permissions précises sur plusieurs modules.',
                        'context'     => 'Votre organisation crée un nouveau poste de "Chargé de clientèle". Ces employés doivent : voir les visiteurs (mais ne pas les supprimer), créer des tâches (mais pas des projets), accéder en lecture seule aux documents. Aucun accès RH ni Comptabilité.',
                        'steps'       => [
                            'Dans **Paramètres → Rôles → + Nouveau rôle**.',
                            'Nommez le rôle "Chargé(e) de clientèle", description : "Accès limité client-facing".',
                            'Module **Visiteurs** : cochez Voir ✓, Créer ✓, Modifier ✓ — décochez Supprimer ✗, Exporter ✗.',
                            'Module **Tâches** : cochez Voir ✓, Créer tâches ✓ — décochez Créer projets ✗, Supprimer ✗.',
                            'Module **Documents** : cochez Voir ✓, Télécharger ✓ — décochez Importer ✗, Supprimer ✗, Partager ✗.',
                            'Module **RH** : tout décoché ✗.',
                            'Module **Comptabilité** : tout décoché ✗.',
                            'Cliquez **Enregistrer le rôle**.',
                            'Assignez ce rôle à 2 utilisateurs existants depuis **Utilisateurs → [nom] → Modifier le rôle**.',
                            'Testez en vous connectant avec un de ces comptes : vérifiez que le bouton "Supprimer" est absent dans Visiteurs et que le menu RH n\'est pas visible.',
                        ],
                        'expected_result' => 'Le rôle "Chargé(e) de clientèle" est créé et appliqué à 2 utilisateurs. Les utilisateurs ayant ce rôle ne voient pas RH ni Comptabilité dans le menu. Dans Visiteurs, le bouton Supprimer est absent. Dans Documents, le bouton Importer est absent.',
                    ],
                    'en' => [
                        'title'       => 'Configure Permissions for a Custom Role',
                        'description' => 'Create a "Client Relations Officer" role with precise permissions across multiple modules.',
                        'context'     => 'Your organization is creating a new "Client Relations Officer" position. These employees must: view visitors (but not delete them), create tasks (but not projects), have read-only access to documents. No HR or Accounting access.',
                        'steps'       => [
                            'In **Settings → Roles → + New Role**.',
                            'Name the role "Client Relations Officer", description: "Limited client-facing access".',
                            'Module **Visitors**: check View ✓, Create ✓, Edit ✓ — uncheck Delete ✗, Export ✗.',
                            'Module **Tasks**: check View ✓, Create Tasks ✓ — uncheck Create Projects ✗, Delete ✗.',
                            'Module **Documents**: check View ✓, Download ✓ — uncheck Import ✗, Delete ✗, Share ✗.',
                            'Module **HR**: all unchecked ✗.',
                            'Module **Accounting**: all unchecked ✗.',
                            'Click **Save Role**.',
                            'Assign this role to 2 existing users via **Users → [name] → Edit Role**.',
                            'Test by logging in with one of these accounts: verify the "Delete" button is absent in Visitors and the HR menu is not visible.',
                        ],
                        'expected_result' => 'The "Client Relations Officer" role is created and applied to 2 users. Users with this role do not see HR or Accounting in the menu. In Visitors, the Delete button is absent. In Documents, the Import button is absent.',
                    ],
                ],
            ],

            [
                'slug'                => 'admin-sauvegarde',
                'category'            => 'admin',
                'difficulty'          => 'intermediate',
                'duration_minutes'    => 20,
                'prerequisites'       => ['admin-ajouter-utilisateur'],
                'learning_objectives' => [
                    'Lancer une sauvegarde manuelle',
                    'Vérifier l\'intégrité de la sauvegarde',
                    'Configurer la sauvegarde automatique',
                    'Simuler une restauration partielle',
                ],
                'order'      => 20,
                'is_featured' => false,
                'translations' => [
                    'fr' => [
                        'title'       => 'Effectuer et tester une sauvegarde',
                        'description' => 'Lancez une sauvegarde complète de vos données, vérifiez son intégrité et configurez les sauvegardes automatiques.',
                        'context'     => 'Avant une migration de serveur planifiée pour demain, votre DSI vous demande d\'effectuer une sauvegarde manuelle complète de toutes les données de l\'organisation et de vérifier qu\'elle est exploitable.',
                        'steps'       => [
                            'Accédez à **Paramètres → Administration → Sauvegardes**.',
                            'Consultez l\'historique : vérifiez la dernière sauvegarde automatique (date, taille, statut).',
                            'Cliquez **+ Sauvegarde manuelle maintenant**.',
                            'Sélectionnez le périmètre : **Toutes les données** (BDD + fichiers + paramètres).',
                            'Lancez la sauvegarde. Une barre de progression s\'affiche (quelques minutes).',
                            'Une fois terminée, cliquez sur la sauvegarde dans la liste et vérifiez : statut = "Réussie", taille (doit être non nulle), hash de vérification.',
                            'Cliquez **Télécharger le rapport de sauvegarde** pour avoir la preuve documentée.',
                            'Configurez la sauvegarde automatique : **Planification → Quotidienne à 02h00**, rétention = 30 jours.',
                            'Testez la restauration partielle : cliquez **Restaurer** puis sélectionnez "Paramètres uniquement" (sans écraser les données).',
                            'Vérifiez que les paramètres se restaurent correctement.',
                        ],
                        'expected_result' => 'La sauvegarde manuelle est réussie avec un statut "Réussie" et un hash de vérification valide. La sauvegarde automatique quotidienne à 02h00 est configurée. Le rapport de sauvegarde est téléchargé et archivé.',
                    ],
                    'en' => [
                        'title'       => 'Perform and Test a Backup',
                        'description' => 'Launch a full data backup, verify its integrity, and configure automatic backups.',
                        'context'     => 'Before a server migration planned for tomorrow, your IT manager asks you to perform a complete manual backup of all organizational data and verify it is usable.',
                        'steps'       => [
                            'Go to **Settings → Administration → Backups**.',
                            'Check the history: verify the last automatic backup (date, size, status).',
                            'Click **+ Manual Backup Now**.',
                            'Select scope: **All Data** (database + files + settings).',
                            'Start the backup. A progress bar displays (a few minutes).',
                            'Once complete, click on the backup in the list and verify: status = "Successful", size (must be non-zero), verification hash.',
                            'Click **Download Backup Report** to get documented proof.',
                            'Configure automatic backup: **Schedule → Daily at 2:00 AM**, retention = 30 days.',
                            'Test partial restoration: click **Restore** then select "Settings only" (without overwriting data).',
                            'Verify that settings are restored correctly.',
                        ],
                        'expected_result' => 'The manual backup is successful with "Successful" status and a valid verification hash. The daily automatic backup at 2:00 AM is configured. The backup report is downloaded and archived.',
                    ],
                ],
            ],

        ];

        foreach ($cases as $caseData) {
            PracticalCase::updateOrCreate(
                ['slug' => $caseData['slug']],
                $caseData
            );
        }
    }
}
